apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xf-xpla-node01-data
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: Pod
metadata:
  name: xpla-node01-pod
  labels:
    app: xpla-node
    node: xpla-node03
spec:
  restartPolicy: Never
  volumes:
    - name: xpla-node-data
      persistentVolumeClaim:
        claimName: xpla-node01-data
  containers:
    - name: xpla-node-container
      image: polonaiz/xpla-node:1.1
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"] 
      volumeMounts:
        - mountPath: /data
          name: xpla-node-data
      resources:
        requests:
          memory: "32Gi"
          cpu: "200m"
        limits:
          memory: "32Gi"
          cpu: "200m"
      ports:
        - containerPort: 1317
          name: lcd
---
apiVersion: v1
kind: Service
metadata:
  name: xpla-lcd01
spec:
  selector:
    app: xpla-node
    node: xpla-node03
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 1317
    targetPort: 1317
---
