apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terra-classic-node-data-std
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti # need to be increased later
