apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terra-classic-node-data
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1600Gi # need to be increased later
