apiVersion: v1
kind: Pod
metadata:
  name: terra-classic-node-pod
  labels:
    app: terra-classic-node-label
spec:
  restartPolicy: Never
  volumes:
    - name: terra-classic-node-data
      persistentVolumeClaim:
        claimName: terra-classic-node-data-pvc
    # - name: quicksync-downloader-data
    #   persistentVolumeClaim:
    #     claimName: quicksync-downloader-data
  containers:
    - name: terra-classic-node-container
      image: polonaiz/terra-classic-node
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"] 
      volumeMounts:
        - mountPath: /data
          name: terra-classic-node-data
        # - mountPath: /download
        #   name: quicksync-downloader-data
      resources:
        requests:
          memory: "32Gi"
          cpu: "200m"
        limits:
          memory: "32Gi"
          cpu: "200m"
      ports:
        - containerPort: 1317
          name: lcd
        # to be changed terrad start --x-crisis-skip-assert-invariants
