apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quicksync-downloader-data
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Ti

---
apiVersion: v1
kind: Pod
metadata:
  name: quicksync-downloader-pod
spec:
  restartPolicy: Never
  volumes:
    - name: quicksync-downloader-data
      persistentVolumeClaim:
        claimName: quicksync-downloader-data
  containers:
    - name: quicksync-downloader-container
      image: polonaiz/terra-classic-node
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"] 
      volumeMounts:
        - mountPath: /data
          name: quicksync-downloader-data
      resources:
        requests:
          memory: "8Gi"
          cpu: "200m"
        limits:
          memory: "8Gi"
          cpu: "200m"

# apt-get install wget liblz4-tool aria2 -y
# aria2c -x4 https://dl2.quicksync.io/columbus-5-archive.20220830.1141.tar.lz4